project_id = "sspayyqutfdjusqcaqwy"

[functions.invite-staff]
verify_jwt = true

[functions.register-clinic]
verify_jwt = false

[functions.check-slug]
verify_jwt = false

[functions.appointment-reminders]
verify_jwt = false
